---
version: "3.8"
services:
  movies:
    image: vani12346/moviesrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: vani12346/trainrepo:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: vani12346/dthrepo:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: vani12346/rechargerepo:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
